apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: oscarzzz/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-servce
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
             # name can be anything, we chose PGPASSWORD because it is the variable name the server applications

              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
                  #k8s find the secret with the name, find the key value pair with a key name of 'PGPASSWORD', pass in its value as the value for env var 'PGPASSWORD' (not the
